version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:40" # El puerto 8080 en el host mapeado al puerto 40 en el contenedor
    volumes:
      - ./web:/var/www/html # Monta la carpeta web en el contenedor
    depends_on:
      - db # Indica que el servicio web depende del servicio de base de datos
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root # Contraseña del usuario root
      MYSQL_DATABASE: nombre_base_datos # Nombre de la base de datos
    ports:
      - "3306:3306" # Puerto de MySQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge # Usa el driver de red bridge
